# Generated by Django 4.0.1 on 2022-02-18 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_about_me'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
